apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "kubernetes.io/hostname"
                    operator: In
                    values:
                      - 2node
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: sonarr
          ports:
            - containerPort: 8989
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: shows
              mountPath: /shows
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: shows
          hostPath:
            path: /arr/media/shows
          # nfs:
          #   path: /arr/media/shows
          #   server: 10.43.12.13
        - name: config
          nfs:
            path: /arr/configs/sonarr
            server: 10.43.12.13
        - name: downloads
          hostPath:
            path: /arr/downloads
          # nfs:
          #   path: /arr/downloads
          #   server: 10.43.12.13
