apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "kubernetes.io/hostname"
                    operator: In
                    values:
                      - 2node
      terminationGracePeriodSeconds: 0
      dnsConfig:
        nameservers:
          - "10.64.0.1"
      containers:
        - name: gluetun
          image: qmcgaw/gluetun
          envFrom:
            - configMapRef:
                name: vpn
            - secretRef:
                name: vpn
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_MODULE
        - name: qbittorrent
          image: linuxserver/qbittorrent:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          envFrom:
            - configMapRef:
                name: qbittorrent
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 6881
              protocol: TCP
            - containerPort: 6881
              protocol: UDP
          volumeMounts:
            - name: downloads
              mountPath: /downloads
            - name: config
              mountPath: /config
      volumes:
        - name: config
          nfs:
            path: /arr/configs/qbittorrent
            server: 10.43.12.13
        - name: downloads
          hostPath:
            path: /arr/downloads
        #   nfs:
        #     path: /arr/downloads
        #     server: 10.43.12.13
