apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dnsmasq
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
