apiVersion: v1
kind: Service
metadata:
  name: pihole
spec:
  type: LoadBalancer
  ports:
    - name: dns
      port: 53
      targetPort: 53
    - name: web
      port: 8053
      targetPort: 80
  selector:
    app: pihole
