apiVersion: v1
kind: Service
metadata:
  name: minecraft-svc
  namespace: minecraft
spec:
  type: LoadBalancer
  ports:
    - port: 42069
      targetPort: 25565
      name: minecraft
    - port: 19132
      targetPort: 19132
      name: bedrock
      protocol: UDP
  selector:
    app: minecraft
