apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jellyfin
  name: jellyfin
  namespace: jellyfin
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jellyfin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "kubernetes.io/hostname"
                    operator: In
                    values:
                      - 2node
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: jellyfin-env
          ports:
            - containerPort: 8096
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
            - name: media
              mountPath: /media
      restartPolicy: Always
      volumes:
        - name: data
          nfs:
            server: 10.43.12.13 # icky but necessary for nfs to work. cannot reference dns name
            path: /arr/data
        - name: config
          nfs:
            server: 10.43.12.13 # icky but necessary for nfs to work. cannot reference dns name
            path: /arr/configs/jellyfin
        - name: media
          hostPath:
            path: /arr/media
          # nfs:
          #   server: 10.43.12.13 # icky but necessary for nfs to work. cannot reference dns name
          #   path: /arr/media
